name: Build

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: Setup MSYS2 environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: mingw-w64-ucrt-x86_64-gcc automake autoconf pkg-config make zip patch tar

    - name: Build binaries
      run: make -j2 MAKE="make -j2"

    - uses: actions/upload-artifact@v4
      with:
        name: zip-archive
        path: build/gettext-tools*.zip
